### ISSUE TITLE
Sites: freebitco.in

### ISSUE THREAD

**Issue by TristanIvanov** [GamblingWonder/Dicebot#9]
Hi, just as a reminder...
betting still does not work as mentioned here: https://github.com/Seuntjie900/DiceBot/issues/81

have a good day!

**Comment by Covaooo** [comment]
Hello.  In bot version 4.2.9.1, a bug for Freebitco.in is fixed???

**Comment by user39284** [comment]
Hi, this is marked as closed, but still getting same error in 4.2.10.8 and 4.2.10.11
